name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: Hamba-Allah-Team/SIM-backend
        token: ${{ secrets.GITHUB_TOKEN }}
        path: SIM-backend

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Docker Image
      run: |
        # Dapatkan nama branch saat ini untuk tag image Docker
        IMAGE_BRANCH=${{ github.ref_name }}
        
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sim-backend:$IMAGE_BRANCH .
        docker push ${{ secrets.DOCKER_USERNAME }}/sim-backend:$IMAGE_BRANCH
        
      working-directory: SIM-backend

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          BRANCH=${{ github.ref_name }}
          IMAGE=${{ secrets.DOCKER_USERNAME }}/sim-backend:$BRANCH

          echo "Login Docker & pull latest image..."
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull $IMAGE
          
          echo "Deploying to server ..."
          cd /home/pbluser/codes/SIM-backend
          git fetch origin
          git checkout $BRANCH
          git pull origin $BRANCH
          export TAG=$BRANCH
          export USERNAME=${{ secrets.DOCKER_USERNAME }}

          echo "Stopping old container..."
          docker compose down

          echo "Running containers..."
          docker compose up -d
